#ifndef LEDMRX_CONFIG_H
#define LEDMRX_CONFIG_H

/*Enter the macro instead of PORTx, PINx */
#define LEDMRX_ROW_PORT	  GPIOA

#define LEDMRX_ROW0_PIN   LEDMRX_ROW_PORT,0
#define LEDMRX_ROW1_PIN   LEDMRX_ROW_PORT,1
#define LEDMRX_ROW2_PIN   LEDMRX_ROW_PORT,2
#define LEDMRX_ROW3_PIN   LEDMRX_ROW_PORT,3
#define LEDMRX_ROW4_PIN   LEDMRX_ROW_PORT,4
#define LEDMRX_ROW5_PIN   LEDMRX_ROW_PORT,5
#define LEDMRX_ROW6_PIN   LEDMRX_ROW_PORT,6
#define LEDMRX_ROW7_PIN   LEDMRX_ROW_PORT,7


#define LEDMRX_COL_PORT	  GPIOB

#define LEDMRX_COL0_PIN   LEDMRX_COL_PORT,0
#define LEDMRX_COL1_PIN   LEDMRX_COL_PORT,1
#define LEDMRX_COL2_PIN   LEDMRX_COL_PORT,5
#define LEDMRX_COL3_PIN   LEDMRX_COL_PORT,6
#define LEDMRX_COL4_PIN   LEDMRX_COL_PORT,7
#define LEDMRX_COL5_PIN   LEDMRX_COL_PORT,8
#define LEDMRX_COL6_PIN   LEDMRX_COL_PORT,9
#define LEDMRX_COL7_PIN   LEDMRX_COL_PORT,10


#endif




